[package]
name = "prime_number_finder"
version = "0.1.0"
authors = ["Ole"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'